ARCPROCDIR = ''  # Directory to house archives that have been processed
ARCSVDIR = ''  # Directory to house archives that have been downloaded but not processed

# DBCONNSTR is moved to dsn.py

MASTERDIR = ''  # Master directory for weekly candidate and committee master files

RPTERRDIR  = 'errorlogs/' # Directory to house error logs generated when a field can't be parsed
RPTHOLDDIR = 'hold/'      # Directory to house electronically filed reports that cannot be processed
RPTOUTDIR  = 'output/'    # Directory to house data files generated by parse_reports
RPTPROCDIR = 'processed/' # Directory to house electronically filed reports that have been processed
RPTRVWDIR  = 'review/'    # Directory to house electronically filed reports that could not be imported and need to be reviewed
RPTSVDIR   = 'import/'    # Directory to house electronically filed reports that have been downloaded but not processed
