ARCPROCDIR = ''  # Directory to house archives that have been processed
ARCSVDIR = ''  # Directory to house archives that have been downloaded but not processed

# DBCONNSTR is moved to dsn.py

MASTERDIR = ''  # Master directory for weekly candidate and committee master files

RPTERRDIR  = '2015/errorlogs/' # Directory to house error logs generated when a field can't be parsed
RPTHOLDDIR = '2015/hold/'      # Directory to house electronically filed reports that cannot be processed
RPTOUTDIR  = '2015/output/'    # Directory to house data files generated by parse_reports
RPTPROCDIR = '2015/processed/' # Directory to house electronically filed reports that have been processed
RPTRVWDIR  = '2015/review/'    # Directory to house electronically filed reports that could not be imported and need to be reviewed
RPTSVDIR   = '2015/import/'    # Directory to house electronically filed reports that have been downloaded but not processed
